-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT S.USER_ID) USERS FROM ONLINE_SALE S
INNER JOIN USER_INFO I
ON S.USER_ID = I.USER_ID
AND GENDER IS NOT NULL

GROUP BY YEAR, MONTH, GENDER

ORDER BY YEAR ASC, MONTH ASC, GENDER ASC