-- 코드를 입력하세요
# 1. 각 차의 30일 할인 PLAN을 JOIN시켜 1개의 테이블로 만들기 (1&3번 테이블 조인)
WITH CAR_AND_DISCOUNT AS (
SELECT CAR_ID, C.CAR_TYPE, DAILY_FEE, DISCOUNT_RATE  FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON C.CAR_TYPE = DP.CAR_TYPE
    AND DP.DURATION_TYPE LIKE "30%"
)

# 대여가능 기간 조건을 WHERE에서 적용하기
SELECT CAR_ID, CAR_TYPE, FLOOR(30*DAILY_FEE*(1-DISCOUNT_RATE/100) ) FEE FROM CAR_AND_DISCOUNT
WHERE CAR_ID NOT IN 
    # 겹치는 구간에 있는 CAR_ID들
    ( SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' # 두 구간이 겹칠 필요충분 부등식

    ) 
AND  30*DAILY_FEE*(1-DISCOUNT_RATE/100) < 2000000
AND 30*DAILY_FEE*(1-DISCOUNT_RATE/100) >= 500000

ORDER BY FEE DESC,  CAR_TYPE ASC , CAR_ID DESC