-- 코드를 입력하세요

# FOOD_TYPE별로 MAX_FAVORITE를 구하는 TABLE 생성
WITH MAX_FAVORITE_TB AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITE
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

# FOOD_TYPE별로 MAX_FAVORITE인 것만 추출
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
# SELECT *
FROM REST_INFO RI

INNER JOIN MAX_FAVORITE_TB MFT
ON RI.FOOD_TYPE = MFT.FOOD_TYPE AND RI.FAVORITES = MFT.MAX_FAVORITE

ORDER BY FOOD_TYPE DESC