-- 코드를 입력하세요
SELECT  YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT S.USER_ID) PUCHASED_USERS 
, ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT  COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%' ) ,1) PUCHASED_RATIO

FROM ONLINE_SALE S
INNER JOIN USER_INFO I
ON S.USER_ID = I.USER_ID
AND JOINED LIKE '2021%'

GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)

ORDER BY YEAR ASC, MONTH ASC