-- 코드를 입력하세요

SELECT FLAVOR FROM
(SELECT FLAVOR , J.TOTAL_ORDER + COALESCE(H.TOTAL_ORDER , 0) SUM_ORDER 
FROM ( SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM JULY GROUP BY FLAVOR) J  # FLAVOR로 JOIN하기 위해서, 합쳐주기
LEFT JOIN FIRST_HALF H
USING(FLAVOR)

ORDER BY SUM_ORDER DESC
) TMP
LIMIT 3