-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOTAL_SALES FROM
( SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES FROM USED_GOODS_BOARD WHERE STATUS ='DONE' GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000) TMP

LEFT JOIN USED_GOODS_USER U
ON TMP.WRITER_ID = U.USER_ID

ORDER BY TOTAL_SALES ASC


# SELECT * FROM USED_GOODS_BOARD
# WHERE WRITER_ID = 'sangyoung58'