-- 코드를 입력하세요
SELECT P1.CATEGORY, P2.MAX_PRICE, P1.PRODUCT_NAME FROM FOOD_PRODUCT P1
INNER JOIN 
    (SELECT CATEGORY, MAX(PRICE) MAX_PRICE FROM FOOD_PRODUCT GROUP BY CATEGORY) P2
ON P1.CATEGORY = P2.CATEGORY AND P1.PRICE = P2.MAX_PRICE

WHERE P1.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY MAX_PRICE DESC
    