# ID 별로 REVIEW 횟수를 적은 TABLE 생성
WITH MAX_ID AS (
SELECT MEMBER_ID, COUNT(*) REVIEW_CNT FROM REST_REVIEW
GROUP BY MEMBER_ID)

# REVIEW 횟수가 최대인 MEMBER_ID 찾아서 가져오기 & MEMBER_PROFILE TABLE과 JOIN
SELECT MEMBER_NAME, REVIEW_TEXT, LEFT(REVIEW_DATE,10) REVIEW_DATE FROM REST_REVIEW R

INNER JOIN MEMBER_PROFILE P
ON R.MEMBER_ID = P.MEMBER_ID
AND R.MEMBER_ID = (SELECT MEMBER_ID FROM MAX_ID ORDER BY REVIEW_CNT DESC LIMIT 1)

ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC