-- 코드를 입력하세요
# 1. BOOK & AUTHOR의 정보를 담은 테이블 생성
WITH BOOK_AUTHOR AS (
SELECT B.BOOK_ID, CATEGORY, PRICE, PUBLISHED_DATE, A.AUTHOR_ID, A.AUTHOR_NAME FROM BOOK B
LEFT JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID)


SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) TOTAL_SALES FROM BOOK_SALES S
INNER JOIN BOOK_AUTHOR BA
ON S.BOOK_ID = BA.BOOK_ID
AND SALES_DATE LIKE '2022-01%'

GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC